# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions
            
alias lo="exit"
alias ls="ls -F"
alias more="less"
alias rm="rm -i"
alias ssh="ssh -o VisualHostKey=yes"
alias vi='vim'

set -o vi

export ICHABOD_DB_USERNAME=ichabod
export ICHABOD_DB_PASSWORD=vagrant
rvm use 2.1.3@ichy
